'use client'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import CustomProvider from '@/redux/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<head>
				<title>
					Sistema Informático de Gestión de las Elecciones de la FEU
				</title>
			</head>
			<body className={inter.className}>
				<CustomProvider>{children}</CustomProvider>
			</body>
		</html>
	)
}
